apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-shared
  labels:
    type: dep
spec:
  replicas: 4
#  strategy:
#    type: Recreate
  selector:
    matchLabels:
      name: worker-shared
  template:
    metadata:
      annotations:
        date: "kurwa"
      labels:
        name: worker-shared
    spec:
      restartPolicy: Always
      containers:
      - name: worker-1
        image: debian:9
        imagePullPolicy: IfNotPresent
        command:
        - sleep
        - "3600"
