apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-shared
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-shared
  template:
    metadata:
      labels:
        name: worker-shared
    spec:
      restartPolicy: Always
      containers:
      - name: worker-1
        image: debian:8
        imagePullPolicy: IfNotPresent
        command:
        - sleep
        - "3600"
