apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  namespace: default
spec:
  restartPolicy: Always
  containers:
  - name: busybox
    image: busybox
    imagePullPolicy: IfNotPresent
    command:
    - sleep
    - "3600"
