apiVersion: v1
kind: Pod
metadata:
  name: pod-with-multiple-containers
spec:
  containers:
  - name: busybox-container
    image: busybox
    command:
    - sleep
    - "3600"
  - name: debina-container
    image: debian
    command:
    - sleep
    - "3600"
