---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: worker-shared-v
  labels:
    name: shared
spec:
  capacity:
    storage: 1Gi
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  hostPath:
    # directory location on host
    path: /data/kta-shared-v/
    # this field is optional
    type: DirectoryOrCreate


