---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kta-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kta
        cmp: app
    spec:
      containers:
        - name: kta-app
          image: mrupgrade/kta:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: KTA_DEBUG_VAR
              value: Value from deployment definition
            - name: KTA_LOG_PATH
              value: /log/
          volumeMounts:
            - mountPath: /log/
              name: log
      volumes:
        - name: log
          persistentVolumeClaim:
            claimName: "kta-log-vc"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: kta-log-vc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: kta-log-v
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    # directory location on host
    path: /data/kta-log-v/
    # this field is optional
    type: DirectoryOrCreate


---
apiVersion: v1
kind: Service
metadata:
  name: kta
  labels:
    app: kta
    cmp: app
spec:
  selector:
    app: kta
    cmp: app
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 10080
      # Port to forward to inside the pod
      targetPort: 8080
      # Port accessible outside cluster
      nodePort: 30010
  type: NodePort
