apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-shared
  namespace: default
spec:

  selector:
    matchLabels:
      name: worker-shared
  template:
    metadata:
      labels:
        name: worker-shared
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - sleep
        - "3600"
