apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: kta-log-v
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    # directory location on host
    path: /data/pv-1
    # this field is optional
    type: Directory
