apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: pv-1
spec:
  capacity:
    storage: "1Gi"
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    # directory location on host
    path: /data/pv-1
    # this field is optional
    type: Directory
