apiVersion: v1
kind: Pod
metadata:
  name: pod-lister
spec:
  serviceAccountName: pod-reader-sa
  restartPolicy:
  containers:
  - name: kubectl
    image: dtzar/helm-kubectl:2.11.0
    imagePullPolicy: IfNotPresent
    command: |
    - kubectl
    - get
    - pods
