apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      name: worker
  template:
    metadata:
      labels:
        name: worker
    spec:
      nodeSelector:
        paperspace.com/pool-name: service-small
      containers:
      - name: container
        image: debian
        imagePullPolicy: IfNotPresent
        command:
        - sleep
        - "100000"
        volumeMounts:
        - mountPath: /data/
          name: data

      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: gp2-pvc
