---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kta-webapp
spec:
  selector:
    matchLabels:
      app: kta-webapp
  template:
    metadata:
      labels:
        app: kta-webapp
    spec:
      containers:
      - name: app
        image: mrupgrade/kta-webapp-flask:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: KTA_DEBUG_VAR
          value: Value from deployment definition
        - name: KTA_LOG_PATH
          value: /log/
        volumeMounts:
        - mountPath: /log/
          name: log
      volumes:
      - name: log
        persistentVolumeClaim:
          claimName: "kta-log-vc"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kta-log-vc
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: kta-log-v
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    # directory location on host
    path: /data/kta-log-v/
    # this field is optional
    type: DirectoryOrCreate


---
apiVersion: v1
kind: Service
metadata:
  name: kta-webapp
spec:
  selector:
    app: kta-webapp
  type: ClusterIP
  ports:
  - protocol: "TCP"
    # Port accessible inside cluster
    port: 8080
    # Port to forward to inside the pod
    targetPort: 8080
    # Port accessible outside cluster
