---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kta-db
spec:
  selector:
    matchLabels:
      app: kta
      cmp: db
  template:
    metadata:
      labels:
        app: kta
        cmp: db
    spec:
      containers:
      - name: kta-db
        image: postgres:9.6
        ports:
        - containerPort: 5432
        env:
        - name: PGDATA
          value: pgdata
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: pgdata
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: "kta-db-vc"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kta-db-vc
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: kta-db-v
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    # directory location on host
    path: /data/kta-db/
    # this field is optional
    type: DirectoryOrCreate


---
apiVersion: v1
kind: Service
metadata:
  name: kta-db
  labels:
    app: kta
    cmp: db
spec:
  selector:
    app: kta
    cmp: db
  ports:
  - protocol: "TCP"
    name: db-uri
    # Port accessible inside cluster
    port: 10081
    # Port to forward to inside the pod
    targetPort: 5432

  type: NodePort