apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: date-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: date-job
            image: busybox
            args:
            - /bin/sh
            - -c
            - |
              date >> /data/test

            volumeMounts:
            - mountPath: /data/
              name: data

          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: "worker-shared-pvc"