---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
  labels:
    name: shared
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /data/kta-shared-v/
    type: DirectoryOrCreate


