---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: worker-shared-pvc
spec:
  accessModes:
    - ReadWriteMany
#  volumeMode: Filesystem
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: shared
