apiVersion: batch/v1
kind: Job
metadata:
  name: job-example
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: job-example
        image: busybox
        args: ["ls", "/test2"]
