apiVersion: v1
kind: Pod
metadata:
  name: worker
  namespace: default
spec:
  restartPolicy: Always
  containers:
  - name: busybox/1
    image: busybox
    imagePullPolicy: IfNotPresent
    command:
    - sleep
    - "3600"
